### ISSUE TITLE
Bump from v6.5.5 to v6.5.6 caused `error Command "webpack" not found.` 

### ISSUE THREAD

**Issue by raivil** [shakacode/shakapacker#249]
Started seeing the error after upgrading from v6.5.5 to v6.5.6.
Reversing fixed the issue.

## Expected behavior:
Assets compilation to complete without errors

## Actual behavior:
Failure to complete assets:precompile on production.
```
...suppressed output....
Writing pagy-module.d-2ae43d1f2559cebcbe95eeb7b90519fdd958ee79.ts"

I, [2023-02-14T14:29:14.566397 #7] INFO -- : Compiling...
E, [2023-02-14T14:29:15.520103 #7] ERROR -- :
COMPILATION FAILED:
EXIT STATUS: pid 21 exit 1
OUTPUTS:
yarn run v1.22.19
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command "webpack" not found.
```

## Setup environment:
- Ruby version: 3.1.2
- Rails version:  7.0.4.2
- Shakapacker version: 6.5.5
- yarn packages are installed automatically

### 
Could this be related to an outdated binstub? 
Running `rails webpacker:install` locally again
```
Copying binstubs
       exist    bin
    conflict    bin/webpacker
  Overwrite /bin/webpacker? (enter "h" for help) [Ynaqdhm] d
    #!/usr/bin/env ruby
    
  - require "pathname"
  + ENV["RAILS_ENV"] ||= "development"
  + ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile", __FILE__)
  + 
    require "bundler/setup"
    require "webpacker"
    require "webpacker/webpack_runner"
  - 
  - ENV["RAILS_ENV"] ||= "development"
  - ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile", Pathname.new(__FILE__).realpath)
    
    APP_ROOT = File.expand_path("..", __dir__)
    Dir.chdir(APP_ROOT) do
      Webpacker::WebpackRunner.run(ARGV)
    end
  Retrying...
```

**Comment by justin808** [comment]
@raivil what OS are you using? Do you have the webpack binary installed?

Run
```bash
ls node_modules/.bin/webpack
```

**Comment by raivil** [comment]
@justin808 it runs on Docker (ruby:3.1.2-bullseye).
Some relevant of the commands on docker file are
```
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -y nodejs && npm install --global yarn

RUN gem update --system && gem install bundler -v 2.3.18 --no-document \
    && bundle config --local build.pg --with-pg-config=/usr/bin/pg_config \
    && bundle config set without 'test development' \
    && bundle config set deployment 'true' \
    && bundle install --jobs 5

RUN bundle check || bundle package --all || bundle install --local
```
npm packages are installed when doing assets precompile.
And this is not happening on 6.5.6, only on 6.5.5.

I know this behavior will be deprecated in shakapacker 7, since the warning is pretty clear.

```
$ bundle exec rails assets:precompile
Shakapacker - Automatic installation of yarn packages is deprecated
Automatic installation of yarn packages when assets are precompiled is deprecated and will be removed in Shakapacker v7.
Please ensure you are installing yarn packages explicitly before the asset compilation.
```

**Comment by ahangarha** [comment]
Hi @raivil 
I tried to reproduce the issue but I couldn't. Is it possible for you to create a small repo where we can reproduce this error?

**Comment by ahangarha** [comment]
@raivil Any update?

**Comment by raivil** [comment]
Hey @ahangarha 
I'm sorry. I'd like to help but I don't have the bandwidth at the moment to create a new repo.

**Comment by ahangarha** [comment]
@cseelus May you please create and share a repo so we can reproduce the issue?

**Comment by justin808** [comment]
@cseelus, are you using the docker build or a heroku buildpack?

**Comment by cseelus** [comment]
@justin808 Running on Heroku-22, with Ruby 3.2.1, Node 16.19.1, Yarn 1.22.19 and the following buildpacks: `heroku/ruby, heroku/nodejs, heroku/jemalloc`.

@ahangarha I'm leaving for Spain on thursday and will be back in the office/at my workstation end of month. If this is still an issue then (its no major one anyway, since 6.5.5. works and 6.5.6 seems to work for most users), I'll create a minimal reproducible example and post a link here.

Until then: Thanks for all the hard work in keeping the Webpacker gem alive and well 💚

**Comment by justin808** [comment]
AFAIK, the heroku/nodejs build pack installs yarn dependencies.

Maybe you have the nodejs buildpack **AFTER** the ruby. If so, you'll get the error above, as precompile runs as part of the ruby buildpack.

@ahangarha we probably need to document this.

**Comment by cseelus** [comment]
@justin808 Just switched the buildpack order (with `node` before `ruby`) and can confirm it successfully built with 6.6.0.

**Comment by ahangarha** [comment]
@cseelus Thanks for your time and for helping to figure out the root cause.
@raivil Please let us know if this fixes your issue as well.

**Comment by raivil** [comment]
@ahangarha Version 6.6.0 didn't fix the issue for me.

**Comment by Alex-450** [comment]
Was having the same issue and fixed by adding `yarn install --frozen-lockfile --immutable` to the node setup, as setup-node doesn't cache node_modules.

Not sure if this is also relevant for you @raivil

**Comment by raivil** [comment]
@Alex-450 my setup is currently relying on executing `yarn install` only when `assets:precompile` is executed.  
I'll probably add a step to execute the install anyway, since shakapacker version 7 will no longer execute it with the precompile step.
